sudo: required # This ensures more memory (https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System)

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: osx
      language: generic
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - os: osx
      language: generic
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - MACOS_SWIFT_TESTS=true
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - IOS_SWIFT_TESTS=true
    - os: linux
      language: python
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - KOTLIN_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - RUST_TESTS=true
    - os: linux
      language: rust
      rust: beta
      env:
        - RUST_TESTS=true
    - os: linux
      language: rust
      rust: nightly
      env:
        - RUST_TESTS=true

before_install: . ./.travis/before_install.sh

install: ./.travis/install.sh

script: ./.travis/test.sh

git:
  depth: 10
